'use client';

export interface ExportOptions {
  includeMetadata?: boolean;
  includeDisclaimer?: boolean;
  format: 'pdf' | 'json' | 'txt' | 'markdown';
}

export function exportReportToJSON(
  report: any,
  filename: string = `report-${Date.now()}.json`
): void {
  const dataStr = JSON.stringify(report, null, 2);
  const dataBlob = new Blob([dataStr], { type: 'application/json' });
  downloadFile(dataBlob, filename);
}

export function exportReportToMarkdown(
  report: any,
  filename: string = `report-${Date.now()}.md`
): void {
  const markdown = `# Medical Report: ${report.title}

**Generated:** ${report.generatedAt}

## Symptoms
${report.symptoms.map((s: string) => `- ${s}`).join('\n')}

## Medical Findings
${report.findings}

## Diagnosis
${report.diagnosis}

## Recommendations
${report.recommendations.map((r: string) => `- ${r}`).join('\n')}

## Important Disclaimer
${report.disclaimer}
`;

  const blob = new Blob([markdown], { type: 'text/markdown; charset=utf-8' });
  downloadFile(blob, filename);
}

export function exportReportToText(
  report: any,
  filename: string = `report-${Date.now()}.txt`
): void {
  const text = `
MEDICAL REPORT: ${report.title}
Generated: ${report.generatedAt}
Report ID: ${report.id}

SYMPTOMS:
${report.symptoms.map((s: string) => `  • ${s}`).join('\n')}

MEDICAL FINDINGS:
${report.findings}

DIAGNOSIS:
${report.diagnosis}

RECOMMENDATIONS:
${report.recommendations.map((r: string) => `  • ${r}`).join('\n')}

MEDICAL DISCLAIMER:
${report.disclaimer}

---
This report was generated by MedAI Assistant.
Please consult with a healthcare professional before making any medical decisions.
  `.trim();

  const blob = new Blob([text], { type: 'text/plain; charset=utf-8' });
  downloadFile(blob, filename);
}

export function downloadFile(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    return false;
  }
}

export function generateShareUrl(reportId: string, baseUrl: string = ''): string {
  const url = baseUrl || window.location.origin;
  return `${url}/reports/${reportId}`;
}

export function getReportSummary(report: any): string {
  return `
Medical Report: ${report.title}

Key Symptoms:
${report.symptoms.slice(0, 3).map((s: string) => `• ${s}`).join('\n')}

Findings:
${report.findings.substring(0, 150)}...

Recommendations:
${report.recommendations.slice(0, 2).map((r: string) => `• ${r}`).join('\n')}
  `.trim();
}
