'use client';

import React, { useState } from 'react';
import { generateShareUrl, copyToClipboard } from '@/utils/reportExport';

interface ReportShareProps {
  reportId: string;
  title: string;
  onClose?: () => void;
}

export function ReportShare({ reportId, title, onClose }: ReportShareProps) {
  const [copied, setCopied] = useState(false);
  const [shareMethod, setShareMethod] = useState<'link' | 'email' | 'social'>('link');

  const shareUrl = generateShareUrl(reportId);

  const handleCopyLink = async () => {
    const success = await copyToClipboard(shareUrl);
    if (success) {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleEmailShare = () => {
    const subject = `Medical Report: ${title}`;
    const body = `I'd like to share this medical report with you:\n\n${shareUrl}\n\nThis report was generated by MedAI Assistant.`;
    window.location.href = `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
  };

  const handleWhatsAppShare = () => {
    const text = `Check out this medical report: ${title}\n${shareUrl}`;
    window.open(
      `https://wa.me/?text=${encodeURIComponent(text)}`,
      '_blank'
    );
  };

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-lg shadow-xl max-w-md w-full p-6">
        <div className="flex justify-between items-center mb-4">
          <h2 className="text-xl font-bold text-slate-900">Share Report</h2>
          <button
            onClick={onClose}
            className="text-slate-400 hover:text-slate-600 text-2xl"
          >
            ✕
          </button>
        </div>

        {/* Share Methods */}
        <div className="space-y-4 mb-6">
          {/* Link Share */}
          <div
            className={`p-4 rounded-lg cursor-pointer transition-colors ${
              shareMethod === 'link'
                ? 'bg-medical-primary text-white'
                : 'bg-slate-100 hover:bg-slate-200'
            }`}
            onClick={() => setShareMethod('link')}
          >
            <h3 className="font-semibold mb-2">🔗 Copy Link</h3>
            {shareMethod === 'link' && (
              <div className="mt-3 space-y-2">
                <input
                  type="text"
                  value={shareUrl}
                  readOnly
                  className="w-full px-3 py-2 bg-white text-slate-900 rounded text-sm border border-slate-300"
                />
                <button
                  onClick={handleCopyLink}
                  className={`w-full py-2 rounded font-medium transition-colors ${
                    copied
                      ? 'bg-green-500 text-white'
                      : 'bg-white text-medical-primary hover:bg-slate-50'
                  }`}
                >
                  {copied ? '✓ Copied' : 'Copy Link'}
                </button>
              </div>
            )}
          </div>

          {/* Email Share */}
          <div
            className={`p-4 rounded-lg cursor-pointer transition-colors ${
              shareMethod === 'email'
                ? 'bg-blue-600 text-white'
                : 'bg-slate-100 hover:bg-slate-200'
            }`}
            onClick={() => setShareMethod('email')}
          >
            <h3 className="font-semibold">📧 Share via Email</h3>
            {shareMethod === 'email' && (
              <div className="mt-3">
                <button
                  onClick={handleEmailShare}
                  className="w-full bg-white text-blue-600 hover:bg-slate-50 py-2 rounded font-medium transition-colors"
                >
                  Send Email
                </button>
              </div>
            )}
          </div>

          {/* Social Share */}
          <div
            className={`p-4 rounded-lg cursor-pointer transition-colors ${
              shareMethod === 'social'
                ? 'bg-green-600 text-white'
                : 'bg-slate-100 hover:bg-slate-200'
            }`}
            onClick={() => setShareMethod('social')}
          >
            <h3 className="font-semibold">💬 WhatsApp</h3>
            {shareMethod === 'social' && (
              <div className="mt-3">
                <button
                  onClick={handleWhatsAppShare}
                  className="w-full bg-white text-green-600 hover:bg-slate-50 py-2 rounded font-medium transition-colors"
                >
                  Share on WhatsApp
                </button>
              </div>
            )}
          </div>
        </div>

        {/* Disclaimer */}
        <div className="bg-yellow-50 border border-yellow-200 rounded p-3 text-sm text-yellow-800">
          <p>
            ⚠️ <strong>Important:</strong> Reports contain sensitive medical information.
            Only share with authorized healthcare providers.
          </p>
        </div>

        <button
          onClick={onClose}
          className="w-full mt-4 bg-slate-300 hover:bg-slate-400 text-slate-900 py-2 rounded font-medium transition-colors"
        >
          Close
        </button>
      </div>
    </div>
  );
}
