'use client';

import React, { useState, useEffect } from 'react';
import Link from 'next/link';
import { ReportDisplay, ReportData, ReportShare } from '@/components/ReportView';
import { Loading } from '@/components/Common/Loading';
import { ErrorAlert } from '@/components/Common/Error';
import {
  exportReportToJSON,
  exportReportToMarkdown,
  exportReportToText,
} from '@/utils/reportExport';

interface ReportsPageProps {
  params: {
    id: string;
  };
}

export default function ReportPage({ params }: ReportsPageProps) {
  const [report, setReport] = useState<ReportData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [showShare, setShowShare] = useState(false);
  const [exportFormat, setExportFormat] = useState<'pdf' | 'json' | 'txt' | 'markdown' | null>(
    null
  );

  useEffect(() => {
    const loadReport = async () => {
      try {
        setLoading(true);
        // Simulate fetching report - in real app this would call API
        const mockReport: ReportData = {
          id: params.id,
          conversationId: 'conv-' + params.id,
          title: 'Medical Consultation Report',
          generatedAt: new Date(),
          symptoms: [
            'Persistent headache',
            'Mild fever',
            'Fatigue',
            'Sore throat',
          ],
          findings:
            'Patient presents with classic symptoms of viral infection. \n\nPhysical examination reveals mild pharyngeal erythema and lymphadenopathy. \n\nVital signs are within acceptable range with slight elevation in temperature.',
          diagnosis: 'Suspected viral pharyngitis, likely upper respiratory infection',
          recommendations: [
            'Rest and adequate hydration',
            'Over-the-counter pain relievers for symptomatic relief',
            'Monitor temperature - seek immediate care if exceeds 103°F',
            'Gargle with warm salt water for throat pain',
            'Follow up if symptoms persist beyond 7 days',
          ],
          disclaimer:
            'This report is generated by an AI system and should not be used as a substitute for professional medical advice. Always consult with a licensed healthcare provider for diagnosis and treatment decisions.',
          metadata: {
            doctorName: 'AI Medical Assistant',
            hospitalName: 'MedAI Virtual Clinic',
            consultationDuration: 15 * 60 * 1000, // 15 minutes in ms
          },
        };
        setReport(mockReport);
        setError(null);
      } catch (err) {
        setError('Failed to load report. Please try again.');
        console.error('Error loading report:', err);
      } finally {
        setLoading(false);
      }
    };

    loadReport();
  }, [params.id]);

  const handleExport = (format: 'pdf' | 'json' | 'txt' | 'markdown') => {
    if (!report) return;

    const filename = `report-${report.id}`;

    switch (format) {
      case 'json':
        exportReportToJSON(report, `${filename}.json`);
        break;
      case 'markdown':
        exportReportToMarkdown(report, `${filename}.md`);
        break;
      case 'txt':
        exportReportToText(report, `${filename}.txt`);
        break;
      case 'pdf':
        window.print();
        break;
    }
    setExportFormat(null);
  };

  if (loading) {
    return <Loading message="Loading report..." fullscreen={true} />;
  }

  if (error || !report) {
    return (
      <div className="min-h-screen bg-slate-50 p-4">
        <div className="max-w-4xl mx-auto mt-8">
          <ErrorAlert
            title="Report Load Error"
            message={error || 'Report not found'}
            onRetry={() => window.location.reload()}
          />
          <Link
            href="/dashboard"
            className="inline-block mt-6 bg-medical-primary text-white px-4 py-2 rounded hover:bg-blue-700 transition-colors"
          >
            ← Back to Dashboard
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-slate-50 py-8 px-4">
      {/* Navigation */}
      <div className="max-w-4xl mx-auto mb-6 print:hidden">
        <Link
          href="/dashboard"
          className="inline-flex items-center gap-2 text-medical-primary hover:text-blue-700 font-medium transition-colors"
        >
          ← Back to Consultations
        </Link>
      </div>

      {/* Main Report Container */}
      <div className="max-w-4xl mx-auto">
        <ReportDisplay
          report={report}
          onClose={() => {}}
          showActions={true}
        />
      </div>

      {/* Export Options Modal */}
      {exportFormat && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-40 p-4">
          <div className="bg-white rounded-lg shadow-xl p-6 max-w-sm w-full">
            <h2 className="text-xl font-bold text-slate-900 mb-4">
              Export as {exportFormat.toUpperCase()}
            </h2>
            <p className="text-slate-600 mb-6">
              Choose export format to save your report locally.
            </p>
            <div className="flex gap-3">
              <button
                onClick={() => handleExport(exportFormat)}
                className="flex-1 bg-medical-primary hover:bg-blue-700 text-white py-2 rounded font-medium transition-colors"
              >
                Export
              </button>
              <button
                onClick={() => setExportFormat(null)}
                className="flex-1 bg-slate-300 hover:bg-slate-400 text-slate-900 py-2 rounded font-medium transition-colors"
              >
                Cancel
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Share Modal */}
      {showShare && (
        <ReportShare
          reportId={report.id}
          title={report.title}
          onClose={() => setShowShare(false)}
        />
      )}

      {/* Floating Action Button for Share */}
      <button
        onClick={() => setShowShare(true)}
        className="fixed bottom-8 right-8 bg-medical-primary hover:bg-blue-700 text-white p-4 rounded-full shadow-lg transition-all print:hidden"
        title="Share report"
      >
        🔗
      </button>
    </div>
  );
}
